#!/usr/bin/env python3
"""Validates the extensions in this repository and generates extensions.json for Satellite.

Every top-level folder that contains a manifest.json is an extension. The script checks each manifest
against the rules Satellite applies when it installs one, then writes extensions.json:

    python3 scripts/generate_extensions.py           # validate, then (re)write extensions.json
    python3 scripts/generate_extensions.py --check   # validate; fail if extensions.json is out of date

Entries already in extensions.json that have a "repository" point at an extension kept in another
repository; they are preserved as written. For an extension in this repository, extra fields on its
entry (such as "ref" or "path") are preserved too. Uses only the Python 3 standard library.
"""
import argparse
import json
import os
import re
import sys

MANIFEST = "manifest.json"
INDEX = "extensions.json"
COMMENT = ("Generated by scripts/generate_extensions.py on every push; do not edit by hand. "
           "Add an extension by adding a folder with a manifest.json. "
           "Entries with a \"repository\" point at another repository and are kept as written.")

ID_RE = re.compile(r"^[a-z0-9][a-z0-9._-]{0,63}$")
SETTING_KEY_RE = re.compile(r"^[A-Za-z][A-Za-z0-9_.-]{0,39}$")
NUMBER = r"(?:0|[1-9][0-9]{0,8})"
SEMVER_RE = re.compile(r"^(%s)\.(%s)\.(%s)(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+[0-9A-Za-z.-]+)?$" % (NUMBER, NUMBER, NUMBER))
PARTIAL_RE = re.compile(r"^(%s)(?:\.(%s))?(?:\.(%s))?(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?$" % (NUMBER, NUMBER, NUMBER))

PERMISSIONS = {"storage", "notifications", "open-external", "ui"}
KINDS = {"content-script", "library"}
RUN_AT = {"document_start", "document_end", "document_idle"}
WORLDS = {"isolated", "main"}
SETTING_TYPES = {"string", "number", "boolean", "choice"}
ICON_EXTENSIONS = {".png", ".jpg", ".jpeg", ".svg"}

MAX_EXTENSIONS = 200
MAX_FILE = 2000000
MAX_TOTAL = 10000000
MAX_ICON = 1000000
MAX_SETTINGS = 40


# --- version helpers (mirror Satellite's SemVer / VersionRange) -------------------------------------------

def parse_semver(text):
    match = SEMVER_RE.match(text) if isinstance(text, str) else None
    if not match:
        return None
    pre = match.group(4).split(".") if match.group(4) else []
    return (int(match.group(1)), int(match.group(2)), int(match.group(3)), pre)


def _pre_key(pre):
    # A release sorts after any prerelease of the same version.
    if not pre:
        return (1,)
    return (0,) + tuple((0, int(p), "") if p.isdigit() else (1, 0, p) for p in pre)


def compare(a, b):
    ka = (a[0], a[1], a[2]) + (_pre_key(a[3]),)
    kb = (b[0], b[1], b[2]) + (_pre_key(b[3]),)
    return (ka > kb) - (ka < kb)


def _comparators(token):
    for prefix in ("^", "~", ">=", "<=", ">", "<", "="):
        if token.startswith(prefix):
            op, body = prefix, token[len(prefix):]
            break
    else:
        op, body = "", token
    match = PARTIAL_RE.match(body)
    if not match:
        return None
    parts = [int(g) for g in match.groups()[:3] if g is not None]
    pre = match.group(4).split(".") if match.group(4) else []
    padded = parts + [0] * (3 - len(parts))
    lower = (padded[0], padded[1], padded[2], pre)
    if op == "^":
        if lower[0] > 0 or len(parts) == 1:
            upper = (lower[0] + 1, 0, 0, [])
        elif lower[1] > 0 or len(parts) == 2:
            upper = (0, lower[1] + 1, 0, [])
        else:
            upper = (0, 0, lower[2] + 1, [])
        return [(">=", lower), ("<", upper)]
    if op == "~":
        upper = (lower[0] + 1, 0, 0, []) if len(parts) == 1 else (lower[0], lower[1] + 1, 0, [])
        return [(">=", lower), ("<", upper)]
    if op in (">=", "<=", ">", "<"):
        return [(op, lower)]
    if len(parts) == 1:
        return [(">=", lower), ("<", (lower[0] + 1, 0, 0, []))]
    if len(parts) == 2:
        return [(">=", lower), ("<", (lower[0], lower[1] + 1, 0, []))]
    return [("=", lower)]


def parse_range(text):
    """Returns a list of comparators, [] for "any version", or None when the range is invalid."""
    text = text.strip() if isinstance(text, str) else None
    if text is None:
        return None
    if text in ("", "*"):
        return []
    result = []
    for token in text.split():
        parsed = _comparators(token)
        if parsed is None:
            return None
        result += parsed
    return result


def range_contains(comparators, version):
    for op, bound in comparators:
        c = compare(version, bound)
        if op == "=" and c != 0 or op == ">=" and c < 0 or op == "<=" and c > 0 or op == ">" and c <= 0 or op == "<" and c >= 0:
            return False
    return True


# --- manifest validation ------------------------------------------------------------------------------------

def safe_path(path):
    if not isinstance(path, str) or not path or path.startswith("/") or "\\" in path or "\0" in path:
        return False
    return not any(part in ("", ".", "..") for part in path.split("/"))


def valid_match(pattern):
    if pattern == "<all_urls>":
        return True
    if not isinstance(pattern, str) or "://" not in pattern:
        return False
    scheme, rest = pattern.split("://", 1)
    if scheme not in ("*", "http", "https", "file") or "/" not in rest:
        return False
    host = rest[:rest.index("/")]
    if host == "*":
        return True
    if host.startswith("*."):
        return bool(host[2:]) and "*" not in host[2:]
    if host == "":
        return scheme == "file"
    return "*" not in host


def validate_setting(setting, add):
    if not isinstance(setting, dict):
        add("each entry in \"settings\" must be an object")
        return None
    key = setting.get("key")
    if not isinstance(key, str) or not SETTING_KEY_RE.match(key):
        add("setting key %r must start with a letter and use letters, digits, '.', '-' or '_' (40 characters at most)" % (key,))
        return None
    label = "setting %r: " % key
    kind = setting.get("type")
    if kind not in SETTING_TYPES:
        add(label + "\"type\" must be one of " + ", ".join(sorted(SETTING_TYPES)))
        return key
    title = setting.get("title")
    if not isinstance(title, str) or not (1 <= len(title.strip()) <= 80):
        add(label + "needs a \"title\" of 1-80 characters")
    description = setting.get("description")
    if description is not None and (not isinstance(description, str) or len(description) > 300):
        add(label + "\"description\" must be text of at most 300 characters")
    low, high = setting.get("min"), setting.get("max")
    for name, value in (("min", low), ("max", high)):
        if value is not None and (isinstance(value, bool) or not isinstance(value, (int, float))):
            add(label + "\"%s\" must be a number" % name)
    if isinstance(low, (int, float)) and isinstance(high, (int, float)) and low > high:
        add(label + "\"min\" is greater than \"max\"")

    options = setting.get("options")
    default = setting.get("default")
    if kind == "choice":
        if not isinstance(options, list) or not (1 <= len(options) <= 50):
            add(label + "a choice needs 1-50 \"options\"")
        else:
            values = [o.get("value") if isinstance(o, dict) else None for o in options]
            labels = [o.get("label") if isinstance(o, dict) else None for o in options]
            if not all(isinstance(v, str) and v for v in values) or not all(isinstance(l, str) and l for l in labels) or len(set(values)) != len(values):
                add(label + "options need unique, non-empty \"value\" and \"label\" text")
            elif default is not None and default not in values:
                add(label + "\"default\" must be one of the option values")
    elif options is not None:
        add(label + "only a choice has \"options\"")

    if default is not None and kind != "choice":
        ok = {
            "string": isinstance(default, str) and len(default) <= 2000,
            "number": isinstance(default, (int, float)) and not isinstance(default, bool)
                      and (low is None or default >= low) and (high is None or default <= high),
            "boolean": isinstance(default, bool),
        }[kind]
        if not ok:
            add(label + "\"default\" doesn't fit the type%s" % (" and range" if kind == "number" else ""))
    return key


def validate_extension(folder, path, add):
    """Checks one extension folder. Returns a summary dict, or None if its manifest couldn't be read."""
    def err(message):
        add("%s/%s" % (folder, MANIFEST), message)

    try:
        with open(os.path.join(path, MANIFEST), encoding="utf-8") as handle:
            manifest = json.load(handle)
    except (OSError, ValueError) as exc:
        err("cannot read manifest.json: %s" % exc)
        return None
    if not isinstance(manifest, dict):
        err("manifest.json must contain a JSON object")
        return None

    if not ID_RE.match(folder):
        err("folder name %r must be 1-64 characters: lowercase letters, digits, '.', '-' or '_', starting with a letter or digit" % folder)
    if manifest.get("id") is not None and manifest["id"] != folder:
        err("\"id\" (%s) must match the folder name (%s)" % (manifest["id"], folder))

    for key in ("name", "version", "description"):
        value = manifest.get(key)
        if not isinstance(value, str) or not value.strip():
            err("missing required field \"%s\"" % key)
    version = parse_semver(manifest.get("version"))
    if isinstance(manifest.get("version"), str) and manifest["version"].strip() and version is None:
        err("\"version\" must look like 1.2.3 (got %r)" % manifest["version"])

    author = manifest.get("author")
    author_name = author.get("name") if isinstance(author, dict) else author
    if not isinstance(author_name, str) or not author_name.strip():
        err("missing required field \"author\" (text, or an object with a \"name\")")

    kind = manifest.get("type", "content-script")
    if kind not in KINDS:
        err("\"type\" must be \"content-script\" or \"library\"")
    run_at = manifest.get("run_at", "document_end")
    if run_at not in RUN_AT:
        err("\"run_at\" must be document_start, document_end or document_idle")
    world = manifest.get("world", "isolated")
    if world not in WORLDS:
        err("\"world\" must be \"isolated\" or \"main\"")

    permissions = manifest.get("permissions", [])
    if not isinstance(permissions, list):
        err("\"permissions\" must be a list")
    else:
        for permission in permissions:
            if permission not in PERMISSIONS:
                err("unknown permission %r (known: %s)" % (permission, ", ".join(sorted(PERMISSIONS))))

    homepage = manifest.get("homepage")
    if homepage is not None and not (isinstance(homepage, str) and re.match(r"^https?://[^/\s]+", homepage)):
        err("\"homepage\" must be an http(s) URL")
    minimum = manifest.get("min_app_version")
    if minimum is not None and parse_semver(minimum) is None:
        err("\"min_app_version\" must look like 1.2.3")

    dependencies = manifest.get("dependencies", {})
    if not isinstance(dependencies, dict):
        err("\"dependencies\" must be an object of { \"extension-id\": \"range\" }")
        dependencies = {}
    for dep, requirement in dependencies.items():
        if not ID_RE.match(dep):
            err("dependency %r is not a valid extension id" % dep)
        elif dep == folder:
            err("an extension cannot depend on itself")
        if parse_range(requirement) is None:
            err("dependency %r has an invalid version range %r" % (dep, requirement))

    matches = manifest.get("matches", [])
    excludes = manifest.get("exclude_matches", [])
    js = manifest.get("js", [])
    css = manifest.get("css", [])
    background = manifest.get("background")
    for name, value in (("matches", matches), ("exclude_matches", excludes), ("js", js), ("css", css)):
        if not isinstance(value, list) or not all(isinstance(item, str) for item in value):
            err("\"%s\" must be a list of text" % name)
            return {"folder": folder, "kind": kind, "version": version, "dependencies": dependencies}
    for pattern in matches + excludes:
        if not valid_match(pattern):
            err("invalid match pattern %r" % pattern)

    if kind == "library":
        if not js:
            err("a library needs at least one \"js\" file")
        if background is not None:
            err("a library cannot have a \"background\" script")
    elif kind == "content-script":
        if not matches:
            if js or css:
                err("\"js\" and \"css\" need \"matches\" to say which pages to run on")
            if background is None:
                err("needs \"matches\" with a \"js\" or \"css\" file, or a \"background\" script")
        elif not js and not css:
            err("needs at least one \"js\" or \"css\" file")
    if background is not None:
        if not safe_path(background):
            err("%r is not a valid relative file path" % (background,))
        if world != "isolated":
            err("a \"background\" script needs \"world\": \"isolated\"")

    settings = manifest.get("settings", [])
    if not isinstance(settings, list):
        err("\"settings\" must be a list")
    else:
        if len(settings) > MAX_SETTINGS:
            err("at most %d settings are allowed" % MAX_SETTINGS)
        seen = set()
        for setting in settings:
            key = validate_setting(setting, err)
            if key is not None:
                if key in seen:
                    err("setting %r is listed twice" % key)
                seen.add(key)

    total = os.path.getsize(os.path.join(path, MANIFEST))
    files = list(js) + list(css) + ([background] if isinstance(background, str) else [])
    for name in files:
        if not safe_path(name):
            err("%r is not a valid relative file path" % name)
            continue
        full = os.path.join(path, *name.split("/"))
        if os.path.islink(full) or not os.path.isfile(full):
            err("%r is listed but is not a file in the folder" % name)
            continue
        size = os.path.getsize(full)
        total += size
        if size > MAX_FILE:
            err("%r is larger than %d MB" % (name, MAX_FILE // 1000000))
    if total > MAX_TOTAL:
        err("the extension is larger than %d MB" % (MAX_TOTAL // 1000000))

    icon = manifest.get("icon")
    if isinstance(icon, str) and icon and not icon.startswith("symbol:"):
        full = os.path.join(path, *icon.split("/")) if safe_path(icon) else None
        if os.path.splitext(icon)[1].lower() not in ICON_EXTENSIONS or full is None:
            add("%s/%s" % (folder, MANIFEST), "warning: icon %r is not a .png, .jpg or .svg path, so a generated icon will be used" % icon, warning=True)
        elif not os.path.isfile(full):
            add("%s/%s" % (folder, MANIFEST), "warning: icon %r is missing, so a generated icon will be used" % icon, warning=True)
        elif os.path.getsize(full) > MAX_ICON:
            add("%s/%s" % (folder, MANIFEST), "warning: icon %r is larger than 1 MB, so a generated icon will be used" % icon, warning=True)

    return {"folder": folder, "kind": kind, "version": version, "dependencies": dependencies}


# --- main ---------------------------------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description="Validate extensions and generate extensions.json.")
    parser.add_argument("--check", action="store_true", help="do not write; fail if extensions.json is out of date")
    parser.add_argument("--root", default=os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."),
                        help="repository root (default: the folder above scripts/)")
    args = parser.parse_args()
    root = os.path.abspath(args.root)
    index_path = os.path.join(root, INDEX)

    on_github = os.environ.get("GITHUB_ACTIONS") == "true"
    problems = []

    def add(where, message, warning=False):
        text = message.replace("warning: ", "", 1) if warning else message
        if on_github:
            print("::%s file=%s::%s" % ("warning" if warning else "error", where, text))
        else:
            print("%s: %s: %s" % ("warning" if warning else "error", where, text))
        if not warning:
            problems.append((where, message))

    folders = sorted(
        name for name in os.listdir(root)
        if not name.startswith((".", "_"))
        and os.path.isdir(os.path.join(root, name))
        and not os.path.islink(os.path.join(root, name))
        and os.path.isfile(os.path.join(root, name, MANIFEST)))

    existing = {}
    if os.path.isfile(index_path):
        try:
            with open(index_path, encoding="utf-8") as handle:
                for entry in json.load(handle).get("extensions", []):
                    if isinstance(entry, dict) and isinstance(entry.get("id"), str):
                        existing[entry["id"]] = entry
        except (OSError, ValueError, AttributeError) as exc:
            add(INDEX, "cannot read the existing file (%s); regenerating it from the folders" % exc)

    summaries = {}
    for folder in folders:
        if folder in existing and "repository" in existing[folder]:
            add(INDEX, "%r is listed as coming from another repository but also exists as a folder here" % folder)
        summary = validate_extension(folder, os.path.join(root, folder), add)
        if summary:
            summaries[folder] = summary

    entries = []
    for folder in folders:
        entry = {"id": folder}
        entry.update({k: v for k, v in existing.get(folder, {}).items() if k != "id"})
        entries.append(entry)
    external = [e for i, e in existing.items() if "repository" in e and i not in folders]
    entries += external
    entries.sort(key=lambda e: e["id"])
    if len(entries) > MAX_EXTENSIONS:
        add(INDEX, "more than %d extensions" % MAX_EXTENSIONS)

    # Dependencies must point at a library here (in a satisfying version) or at a listed external extension.
    external_ids = {e["id"] for e in external}
    for folder, summary in summaries.items():
        for dep, requirement in summary["dependencies"].items():
            if dep in external_ids:
                continue
            target = summaries.get(dep)
            if target is None:
                add("%s/%s" % (folder, MANIFEST), "depends on %r, which is not in this repository or listed in extensions.json" % dep)
            elif target["kind"] != "library":
                add("%s/%s" % (folder, MANIFEST), "depends on %r, which is not a library" % dep)
            else:
                comparators = parse_range(requirement)
                if comparators is not None and target["version"] and not range_contains(comparators, target["version"]):
                    add("%s/%s" % (folder, MANIFEST), "needs %r %s, but this repository has version %s" % (dep, requirement, ".".join(map(str, target["version"][:3]))))

    def visit(node, path):
        for dep in summaries.get(node, {}).get("dependencies", {}):
            if dep in path:
                add("%s/%s" % (node, MANIFEST), "circular dependency: %s" % " -> ".join(path + [node, dep]))
                return
            if dep in summaries:
                visit(dep, path + [node])
    for folder in summaries:
        visit(folder, [])

    if problems:
        print("\n%d problem%s found; extensions.json was not changed." % (len(problems), "" if len(problems) == 1 else "s"))
        return 1

    document = {"_comment": COMMENT, "version": 1, "extensions": entries}
    text = json.dumps(document, indent=2, ensure_ascii=False) + "\n"
    current = open(index_path, encoding="utf-8").read() if os.path.isfile(index_path) else None

    if args.check:
        if current != text:
            add(INDEX, "is out of date; run python3 scripts/generate_extensions.py")
            return 1
        print("extensions.json is up to date (%d extensions)." % len(entries))
        return 0

    if current != text:
        with open(index_path, "w", encoding="utf-8") as handle:
            handle.write(text)
        print("Wrote extensions.json with %d extension%s: %s" % (len(entries), "" if len(entries) == 1 else "s", ", ".join(e["id"] for e in entries)))
    else:
        print("extensions.json is already up to date (%d extensions)." % len(entries))
    return 0


if __name__ == "__main__":
    sys.exit(main())
